# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Implementation of logsumexp as a part of core part
#'
#' @param loga log-value.
#' @param logb log-value.
NULL

#' core implementation of the forward-backward algorithm for HMM
#'
#' @param ledata log-evidence matrix.
#' @param workdata an empty matrix.
FwBk <- function(ledata, workdata) {
    .Call('postCP_FwBk', PACKAGE = 'postCP', ledata, workdata)
}

#' core implementation of the max forward-backward algorithm for most probable cp configurations
#'
#' @param ledata log-evidence matrix.
#' @param workdata an empty matrix.
maxFwBk <- function(ledata, workdata) {
    .Call('postCP_maxFwBk', PACKAGE = 'postCP', ledata, workdata)
}

